import type { MatchLog } from '@/types/pipeline';

/**
 * Realistic hotel demo MatchLog entries shown during the guided tour when the pipeline is empty.
 * These are purely client-side — never written to the database.
 * They disappear automatically when the tour ends (tour.active becomes false).
 */
export const TOUR_DEMO_LOGS: MatchLog[] = [
  {
    id: '__demo_1',
    created_at: '2026-02-28T09:14:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_1',
    conversation_id: '__demo_conv_1',
    sender_email: 'james.wilson@gmail.com',
    sender_name: 'James Wilson',
    sender_domain: 'gmail.com',
    subject_hash: 'demo',
    received_at: '2026-02-28T09:14:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1042,
    dossier_ref: 'BKG-2025-0042',
    dossier_name: 'Wilson, James & Sarah — Suite 405',
    confidence: 0.94,
    match_source: 'sender_history',
    match_reasons: [
      'Known guest email — 3 previous stays linked to this booking',
      'Booking reference BKG-2025-0042 found in email thread',
      'Department routed to: Concierge',
    ],
    handler: 'Concierge',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Routed',
    category_color: 'green',
    email_importance: 'normal',
  },
  {
    id: '__demo_2',
    created_at: '2026-02-28T08:47:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_2',
    conversation_id: '__demo_conv_2',
    sender_email: 'noreply@booking.com',
    sender_name: 'Booking.com',
    sender_domain: 'booking.com',
    subject_hash: 'demo',
    received_at: '2026-02-28T08:47:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1187,
    dossier_ref: 'BKG-2025-0187',
    dossier_name: 'Thompson, Emma — Room 201 (Deluxe)',
    confidence: 0.98,
    match_source: 'reference_exact',
    match_reasons: [
      'Booking reference BKG-2025-0187 found in subject line',
      'OTA confirmation from Booking.com',
      'Department routed to: Reservations',
    ],
    handler: 'Reservations',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Routed',
    category_color: 'green',
    email_importance: 'normal',
  },
  {
    id: '__demo_3',
    created_at: '2026-02-27T16:22:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_3',
    conversation_id: '__demo_conv_3',
    sender_email: 'corporate.travel@hartmann-group.de',
    sender_name: 'Hartmann Group Travel',
    sender_domain: 'hartmann-group.de',
    subject_hash: 'demo',
    received_at: '2026-02-27T16:22:00Z',
    has_attachments: true,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1094,
    dossier_ref: 'BKG-2024-0094',
    dossier_name: 'Hartmann Group — Block Booking (12 rooms)',
    confidence: 0.91,
    match_source: 'sender_history',
    match_reasons: [
      'Corporate account linked to 4 previous group bookings',
      'Group booking reference detected in email body',
      'Department routed to: Reservations',
    ],
    handler: 'Reservations',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Routed',
    category_color: 'green',
    email_importance: 'normal',
  },
  {
    id: '__demo_4',
    created_at: '2026-02-27T14:05:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_4',
    conversation_id: '__demo_conv_4',
    sender_email: 'maintenance@premium-lifts.co.uk',
    sender_name: 'Premium Lifts Ltd',
    sender_domain: 'premium-lifts.co.uk',
    subject_hash: 'demo',
    received_at: '2026-02-27T14:05:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1011,
    dossier_ref: 'BKG-2025-0011',
    dossier_name: 'Maintenance — Elevator 2, Floor 3',
    confidence: 0.88,
    match_source: 'kb_party_exact',
    match_reasons: [
      'Registered supplier match: Premium Lifts Ltd',
      'Maintenance keyword routing triggered',
      'Department routed to: Maintenance',
    ],
    handler: 'Maintenance',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Routed',
    category_color: 'green',
    email_importance: 'high',
  },
];

/** Demo items shown in the review queue (60–84 % confidence, pending review). */
export const TOUR_DEMO_QUEUE: MatchLog[] = [
  {
    id: '__demo_q1',
    created_at: '2026-02-28T10:05:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_q1',
    conversation_id: '__demo_conv_q1',
    sender_email: 'emma.thompson92@hotmail.com',
    sender_name: 'Emma Thompson',
    sender_domain: 'hotmail.com',
    subject_hash: 'demo',
    received_at: '2026-02-28T10:05:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1203,
    dossier_ref: 'BKG-2025-0203',
    dossier_name: 'Thompson, Emma — Room 201 (Deluxe)',
    confidence: 0.72,
    match_source: 'kb_party_fuzzy',
    match_reasons: [
      'Guest name fuzzy match — email sender differs from booking email',
      'Check-in date overlap with existing reservation',
      'Department routed to: Front Desk',
    ],
    handler: 'Front Desk',
    action_taken: null,
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'To Review',
    category_color: 'orange',
    email_importance: 'normal',
  },
  {
    id: '__demo_q2',
    created_at: '2026-02-28T07:30:00Z',
    mailbox: 'reservations@grandazurehotel.com',
    email_id: '__demo_email_q2',
    conversation_id: '__demo_conv_q2',
    sender_email: 'banqueting@azureweddings.co.uk',
    sender_name: 'Azure Weddings & Events',
    sender_domain: 'azureweddings.co.uk',
    subject_hash: 'demo',
    received_at: '2026-02-28T07:30:00Z',
    has_attachments: true,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1156,
    dossier_ref: 'BKG-2025-0156',
    dossier_name: 'Azure Weddings — Grand Ballroom (June 14)',
    confidence: 0.68,
    match_source: 'kb_keyword',
    match_reasons: [
      'Event booking keyword match: wedding reception, catering',
      'F&B department routing triggered',
      'Department routed to: F&B',
    ],
    handler: 'F&B',
    action_taken: null,
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'To Review',
    category_color: 'orange',
    email_importance: 'normal',
  },
];
