import type { MatchLog } from '@/types/pipeline';

/**
 * Realistic demo MatchLog entries shown during the guided tour when the pipeline is empty.
 * These are purely client-side — never written to the database.
 * They disappear automatically when the tour ends (tour.active becomes false).
 */
export const TOUR_DEMO_LOGS: MatchLog[] = [
  {
    id: '__demo_1',
    created_at: '2026-02-28T09:14:00Z',
    mailbox: 'l.brosset@laurencebrosset-avocats.fr',
    email_id: '__demo_email_1',
    conversation_id: '__demo_conv_1',
    sender_email: 'c.liron@smabtp.fr',
    sender_name: 'Charlotte Liron',
    sender_domain: 'smabtp.fr',
    subject_hash: 'demo',
    received_at: '2026-02-28T09:14:00Z',
    has_attachments: true,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1042,
    dossier_ref: 'LB-2024-042',
    dossier_name: 'SMABTP c/ Résidences du Parc',
    confidence: 0.92,
    match_source: 'ai_classifier_global',
    match_reasons: [
      "Expéditeur connu — 14 échanges précédents liés à ce dossier",
      "Référence dossier détectée dans l'objet de l'email",
      "Thème juridique cohérent : assurance construction / CCMI",
    ],
    lawyer: 'L. Brosset',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Classé',
    category_color: 'green',
    email_importance: 'normal',
  },
  {
    id: '__demo_2',
    created_at: '2026-02-28T08:47:00Z',
    mailbox: 'l.brosset@laurencebrosset-avocats.fr',
    email_id: '__demo_email_2',
    conversation_id: '__demo_conv_2',
    sender_email: 'greffe.tc-paris@justice.fr',
    sender_name: 'Greffe TC Paris',
    sender_domain: 'justice.fr',
    subject_hash: 'demo',
    received_at: '2026-02-28T08:47:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: true,
    dossier_id: 987,
    dossier_ref: 'LB-2023-187',
    dossier_name: 'SCI Les Acacias — Redressement judiciaire',
    confidence: 0.78,
    match_source: 'reference_exact',
    match_reasons: [
      "Numéro de RG trouvé dans le corps de l'email",
      "Expéditeur identifié : Greffe du Tribunal de Commerce de Paris",
    ],
    lawyer: 'L. Brosset',
    action_taken: null,
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'À vérifier',
    category_color: 'orange',
    email_importance: 'high',
  },
  {
    id: '__demo_3',
    created_at: '2026-02-27T16:22:00Z',
    mailbox: 'l.brosset@laurencebrosset-avocats.fr',
    email_id: '__demo_email_3',
    conversation_id: '__demo_conv_3',
    sender_email: 'notaire@office-duval.fr',
    sender_name: 'Me Duval',
    sender_domain: 'office-duval.fr',
    subject_hash: 'demo',
    received_at: '2026-02-27T16:22:00Z',
    has_attachments: true,
    is_ebarreau: false,
    matched: true,
    dossier_id: 1105,
    dossier_ref: 'LB-2025-011',
    dossier_name: 'Succession Moreau',
    confidence: 0.89,
    match_source: 'sender_history',
    match_reasons: [
      "Notaire associé à ce dossier depuis l'ouverture du dossier",
      "Mots-clés successoraux détectés : acte de partage, indivision",
    ],
    lawyer: 'L. Brosset',
    action_taken: 'auto_filed',
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Classé',
    category_color: 'green',
    email_importance: 'normal',
  },
  {
    id: '__demo_4',
    created_at: '2026-02-27T14:05:00Z',
    mailbox: 'l.brosset@laurencebrosset-avocats.fr',
    email_id: '__demo_email_4',
    conversation_id: '__demo_conv_4',
    sender_email: 'direction@syndic-montmartre.fr',
    sender_name: 'Syndic Copropriété Montmartre',
    sender_domain: 'syndic-montmartre.fr',
    subject_hash: 'demo',
    received_at: '2026-02-27T14:05:00Z',
    has_attachments: false,
    is_ebarreau: false,
    matched: false,
    dossier_id: null,
    dossier_ref: null,
    dossier_name: null,
    confidence: null,
    match_source: null,
    match_reasons: null,
    lawyer: null,
    action_taken: null,
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'Non classé',
    category_color: 'red',
    email_importance: 'normal',
  },
];

/** Demo items shown in the review queue (60–84 % confidence, pending review). */
export const TOUR_DEMO_QUEUE: MatchLog[] = [
  // Greffe TC Paris — 78 % (re-used from above)
  TOUR_DEMO_LOGS[1]!,
  {
    id: '__demo_q2',
    created_at: '2026-02-28T07:30:00Z',
    mailbox: 'l.brosset@laurencebrosset-avocats.fr',
    email_id: '__demo_email_q2',
    conversation_id: '__demo_conv_q2',
    sender_email: 'huissier@cabinet-leroy.fr',
    sender_name: 'Me Leroy — Huissier de justice',
    sender_domain: 'cabinet-leroy.fr',
    subject_hash: 'demo',
    received_at: '2026-02-28T07:30:00Z',
    has_attachments: true,
    is_ebarreau: false,
    matched: true,
    dossier_id: 863,
    dossier_ref: 'LB-2022-094',
    dossier_name: 'Dupont c/ Bailleur — Expulsion',
    confidence: 0.65,
    match_source: 'kb_party_fuzzy',
    match_reasons: [
      "Nom du défendeur approchant dans la base de connaissances",
      "Thème procédural cohérent : bail, résiliation, voie d'exécution",
    ],
    lawyer: 'L. Brosset',
    action_taken: null,
    reviewed_by: null,
    reviewed_at: null,
    review_approved: null,
    category_label: 'À vérifier',
    category_color: 'orange',
    email_importance: 'normal',
  },
];
